version: '3.7'
services:
  itamaster:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ../../src:/usr/app/src
    ports:
      - "3000:3000"
      - "6006:6006"
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
